project:
  type: website

website:
  title: "pkgtest"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: reference/index.qmd
        text: reference

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

